### ISSUE TITLE
Suggestion: pass interpolation="None" when plotting digits

### ISSUE THREAD

**Issue by msarahan** [jakevdp/sklearn_pydata2015#1]
Notebook 02.2-Basic-Principles.ipynb

Title says it all.  Interpolation makes digit example look higher resolution than it is.

**Comment by msarahan** [comment]
Also in 03.2-Reg...

**Comment by jakevdp** [comment]
Done in 30bd28cfe53350ff7f51e04e7c7f5eef40f20f8b
Thanks!
